# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_summernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fields',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='summer', to='blog.SummerNote'),
            preserve_default=False,
        ),
    ]
