# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0002_update-help_text'),
        ('blog', '0009_post_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_summernote.Attachment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
    ]
