# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180817_0653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
