# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 03:07
from __future__ import unicode_literals

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180817_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summernote',
            name='summer_field',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', null=True),
        ),
    ]
