# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180817_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summernote',
            name='attachment_ptr',
        ),
        migrations.DeleteModel(
            name='SummerNote',
        ),
    ]
