# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
